// Code generated by mockery v2.16.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// JenkinsService is an autogenerated mock type for the JenkinsService type
type JenkinsService struct {
	mock.Mock
}

// CreateJobBuildRun provides a mock function with given fields: name, jobPath, jobParams
func (_m *JenkinsService) CreateJobBuildRun(name string, jobPath string, jobParams map[string]string) error {
	ret := _m.Called(name, jobPath, jobParams)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string, map[string]string) error); ok {
		r0 = rf(name, jobPath, jobParams)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewJenkinsService interface {
	mock.TestingT
	Cleanup(func())
}

// NewJenkinsService creates a new instance of JenkinsService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewJenkinsService(t mockConstructorTestingTNewJenkinsService) *JenkinsService {
	mock := &JenkinsService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
