package keycloak

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type KeycloakRealmUser struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              KeycloakRealmUserSpec   `json:"spec"`
	Status            KeycloakRealmUserStatus `json:"status"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
type KeycloakRealmUserList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []KeycloakRealmUser `json:"items"`
}

type KeycloakRealmUserSpec struct {
	Realm                  string            `json:"realm"`
	Username               string            `json:"username"`
	Email                  string            `json:"email"`
	FirstName              string            `json:"firstName"`
	LastName               string            `json:"lastName"`
	Enabled                bool              `json:"enabled"`
	EmailVerified          bool              `json:"emailVerified"`
	RequiredUserActions    []string          `json:"requiredUserActions"`
	Roles                  []string          `json:"roles"`
	Groups                 []string          `json:"groups"`
	Attributes             map[string]string `json:"attributes"`
	ReconciliationStrategy string            `json:"reconciliationStrategy,omitempty"`
	Password               string            `json:"password"`
	KeepResource           bool              `json:"keepResource"`
}

type KeycloakRealmUserStatus struct {
	Value        string `json:"value"`
	FailureCount int64  `json:"failureCount"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmUser) DeepCopyInto(out *KeycloakRealmUser) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmUser.
func (in *KeycloakRealmUser) DeepCopy() *KeycloakRealmUser {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmUser)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealmUser) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmUserList) DeepCopyInto(out *KeycloakRealmUserList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]KeycloakRealmUser, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmUserList.
func (in *KeycloakRealmUserList) DeepCopy() *KeycloakRealmUserList {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmUserList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *KeycloakRealmUserList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmUserSpec) DeepCopyInto(out *KeycloakRealmUserSpec) {
	*out = *in
	if in.RequiredUserActions != nil {
		in, out := &in.RequiredUserActions, &out.RequiredUserActions
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Roles != nil {
		in, out := &in.Roles, &out.Roles
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Groups != nil {
		in, out := &in.Groups, &out.Groups
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Attributes != nil {
		in, out := &in.Attributes, &out.Attributes
		*out = make(map[string]string, len(*in))
		for key, val := range *in {
			(*out)[key] = val
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmUserSpec.
func (in *KeycloakRealmUserSpec) DeepCopy() *KeycloakRealmUserSpec {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmUserSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *KeycloakRealmUserStatus) DeepCopyInto(out *KeycloakRealmUserStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new KeycloakRealmUserStatus.
func (in *KeycloakRealmUserStatus) DeepCopy() *KeycloakRealmUserStatus {
	if in == nil {
		return nil
	}
	out := new(KeycloakRealmUserStatus)
	in.DeepCopyInto(out)
	return out
}
