basePath: ''
cdPipelineName: platform
cdPipelineStageName: main
name: control-plane-console

enable_branch_provisioners: 1

global:
  edpName: control-plane
  platform: openshift

imageStreamUrlMask: /console/project/{namespace}/browse/images/{stream}

ingress:
  path: /
  required: true
  site: control-plane-console

keycloak:
  realm: admin
keycloakIntegration:
  client:
    name: admin-console-client
    public: false
    secretName: admin-console-client
  enabled: true
  realm: admin
oauthclientName: oauth-admin-console-client

operator:
  clusterRoleName: edp-admin-console-operator-clusterrole-mdtu-ddm-edp-cicd
  serviceAccountName: control-plane-console

projectUrlMask: /console/project/{namespace}/overview

secret:
  sessionSecret:
    suffix: session-secret
