{{ if eq .Values.global.platform "openshift" }}
apiVersion: authorization.openshift.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "controlPlaneConsole.name" .}}-{{ .Release.Namespace }}
roleRef:
  name: edp-{{ include "controlPlaneConsole.name" .}}-clusterrole-{{ .Release.Namespace }}
subjects:
  - kind: ServiceAccount
    name: "{{ .Values.operator.serviceAccountName }}-edp"
    namespace: {{ .Release.Namespace }}
userNames:
  - system:serviceaccount:{{ .Release.Namespace }}:{{ .Values.operator.serviceAccountName }}-edp
groupNames: []
{{ end }}