apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "controlPlaneConsole.name" .}}-{{ .Release.Namespace }}-cluster-role
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.serviceAccountName }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: edp-{{ include "controlPlaneConsole.name" .}}-clusterrole-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io