apiVersion: v1
kind: Secret
metadata:
  name: {{ include "сontrolPlaneConsole.secret.sessionSecret.name" . }}
  labels:
    app: {{ include "controlPlaneConsole.name" . }}
data:
  {{ include "сontrolPlaneConsole.secret.sessionSecret.data" . | nindent 2}}
