apiVersion: v1.edp.epam.com/v1
kind: EDPComponent
metadata:
  name: control-plane-console
spec:
  icon: bW9jaw==
  type: admin-console
  url: {{ template "control-plane-console.url" . }}
  visible: false