{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: edp-resources-admin
roleRef:
  name: edp-resources-admin
  namespace: {{.Release.Namespace}}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.serviceAccountName }}
    namespace: {{.Release.Namespace}}
userNames:
  - system:serviceaccount:{{.Release.Namespace}}:{{ .Values.operator.serviceAccountName }}
groupNames: []
{{- end -}}