{{- if eq .Values.global.platform "openshift" -}}
apiVersion: authorization.openshift.io/v1
kind: RoleBinding
metadata:
  name: control-plane-console-keycloakrealmuser
roleRef:
  name: control-plane-console-keycloakrealmuser
  namespace: user-management
subjects:
  - kind: ServiceAccount
    name: {{ .Values.operator.serviceAccountName }}
    namespace: {{.Values.global.edpName}}
userNames:
  - system:serviceaccount:{{.Values.global.edpName}}:{{ .Values.operator.serviceAccountName }}
groupNames: []
  {{- end -}}