kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    meta.helm.sh/release-name: edp-install
  name: {{ include "controlPlaneConsole.name" .}}
  labels:
    app: {{ include "controlPlaneConsole.name" .}}
spec:
  host: {{ template "control-plane-console.hostname" . }}
  to:
    kind: Service
    name: {{ include "istio.ingressGateway.service.name" . }}
    weight: 100
  port:
    targetPort: http2
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None