kind: Route
apiVersion: route.openshift.io/v1
metadata:
  annotations:
    meta.helm.sh/release-name: edp-install
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  host: {{ template "control-plane-console.hostname" . }}
  to:
    kind: Service
    name: {{ .Values.name }}
    weight: 100
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
  wildcardPolicy: None