kind: Service
apiVersion: v1
metadata:
  name: {{ include "controlPlaneConsole.name" .}}
  labels:
    app: {{ include "controlPlaneConsole.name" .}}
spec:
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  selector:
    app: {{ include "controlPlaneConsole.name" .}}
  type: ClusterIP
  sessionAffinity: None