package edpcomponent

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime"
)

// EDPComponentSpec defines the desired state of EDPComponent
// +k8s:openapi-gen=true
type EDPComponentSpec struct {
	Type    string `json:"type"`
	Url     string `json:"url"`
	Icon    string `json:"icon"`
	Visible bool   `json:"visible"`
}

// EDPComponentStatus defines the observed state of EDPComponent
// +k8s:openapi-gen=true
type EDPComponentStatus struct{}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// EDPComponent is the Schema for the edpcomponents API
// +k8s:openapi-gen=true
// +kubebuilder:subresource:status
// +kubebuilder:resource:path=edpcomponents,scope=Namespaced
type EDPComponent struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec   EDPComponentSpec   `json:"spec,omitempty"`
	Status EDPComponentStatus `json:"status,omitempty"`
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object

// EDPComponentList contains a list of EDPComponent
type EDPComponentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []EDPComponent `json:"items"`
}

type EDPComponentItem struct {
	Type        string
	Url         string
	Icon        string
	Title       string
	Description string
	Visible     string
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EDPComponent) DeepCopyInto(out *EDPComponent) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	out.Status = in.Status
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EDPComponent.
func (in *EDPComponent) DeepCopy() *EDPComponent {
	if in == nil {
		return nil
	}
	out := new(EDPComponent)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EDPComponent) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EDPComponentList) DeepCopyInto(out *EDPComponentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	out.ListMeta = in.ListMeta
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EDPComponent, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EDPComponentList.
func (in *EDPComponentList) DeepCopy() *EDPComponentList {
	if in == nil {
		return nil
	}
	out := new(EDPComponentList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EDPComponentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EDPComponentSpec) DeepCopyInto(out *EDPComponentSpec) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EDPComponentSpec.
func (in *EDPComponentSpec) DeepCopy() *EDPComponentSpec {
	if in == nil {
		return nil
	}
	out := new(EDPComponentSpec)
	in.DeepCopyInto(out)
	return out
}
